apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: accommodation-facility-consumer
  namespace: testies2
spec:
  schedule: 26 * * * *
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: concept-scores 
            component: accommodation-facility-consumer
        spec:
          serviceAccountName: conceptstream-ksa
          restartPolicy: OnFailure
          containers:
            - name: app
              image: eu.gcr.io/testies2-stage/consumer:latest
              imagePullPolicy: Always
              env:

{{ toYaml .Values.containers.env | indent 14 }}

