---
## Add any overrides specific to this env
applications:
  - name: pubsub2kubectl-releases
    namespace: your-argocd-namespace
    additionalLabels: {}
    additionalAnnotations: {}
    project: testies2
    source:
      repoURL: git@github.com:trivago/testies2.git
      targetRevision: master
      path: infrastructure/kubernetes/delivery/manifests/prod-eu-w4/pubsub2kubectl-releases
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: testies2
    syncPolicy:
      automated: {}

  - name: argo-notifications
    namespace: your-argocd-namespace
    additionalLabels: {}
    additionalAnnotations: {}
    project: testies2
    source:
      repoURL: git@github.com:trivago/testies2.git
      targetRevision: master
      path: infrastructure/kubernetes/delivery/manifests/prod-eu-w4/argo-notifications
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: testies2
    syncPolicy:
      automated: {}
